[tools]
java = "latest"
jq = "latest"
maven = "latest"
python = "3"
uv = "latest"

[tasks.generate]
description = "Generate the keyboard files"
run = "mvn compile exec:java"


[tasks.suggest-combos]
description = "Suggest chords to add, ranked by typing benefit"
run = "uv run .mise/tasks/suggest-combos.py"

[tasks.train]
description = "Train chord vocabulary"
run = "uv run train.py"


[tasks.flash]
description = "Flash the keyboard"
depends = "generate"
run = "uv run qmk flash -kb ferris/sweep -km zeitlinger -bl avrdude-split-left"
