#pragma once

// Configure the global tapping term (default: 200ms)
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define TAPPING_TOGGLE 2

#define EXTRA_SHORT_COMBOS
#define COMBO_STRICT_TIMER

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 6
#define TRI_LAYER_ADJUST_LAYER 7

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
