SRC += casemodes.c
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
UNICODEMAP_ENABLE = yes
UNICODE_ENABLE = no
TRI_LAYER_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes

VPATH += keyboards/gboards

